#pragma once

#define IDA_MAINFRAME 101
#define IDI_MAINFRAME 101

#define ID_SUPERBOX 1001
#define ID_CLOSE_DOCUMENT 1002
#define ID_NEXT_FILE 1003
#define ID_PREVIOUS_FILE 1004

#define ID_PAGE_UP 2001
#define ID_PAGE_DOWN 2002

#define ID_FIRST_EDITOR_COMMAND ID_PAGE_UP
#define ID_LAST_EDITOR_COMMAND ID_PAGE_DOWN

#define VERSION_MAJOR 2
#define VERSION_MINOR 0
#define VERSION_REVISION 0
#define VERSION_BUILD 20141207

#define MAKE_VERSION_NUMBER_STRING_EX(major,minor,revision,build) \
	#major "." #minor "." #revision "." #build
#define MAKE_VERSION_NUMBER_STRING(major,minor,revision,build) \
	MAKE_VERSION_NUMBER_STRING_EX(major,minor,revision,build)

#define VERSION_NUMBER \
	VERSION_MAJOR,\
	VERSION_MINOR,\
	VERSION_REVISION,\
	VERSION_BUILD
#define VERSION_NUMBER_STRING \
	MAKE_VERSION_NUMBER_STRING(\
		VERSION_MAJOR, \
		VERSION_MINOR, \
		VERSION_REVISION, \
		VERSION_BUILD)

